# Generated by Django 4.1.5 on 2023-01-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.PositiveIntegerField(editable=False, verbose_name='author_id')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('story', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
